# Generated by Django 2.2.1 on 2019-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='polarity',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='subjectivity',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=6),
        ),
    ]
